---
# tasks file for ocp4-post-infra-nodes

- name: Grab some global cluster trivia for git to use
  k8s_facts:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: infradata

- name: deploy infra-shared machinesets
  vars:
    instance_type: r5.xlarge
    node_labels:
    - infra
    - infra-shared
    zone_suffixes:
      - a
      - b
      - c
    name_identifier: infra-shared
  include_role:
    name: machineset

- name: deploy infra-efk machinesets
  vars:
    instance_type: r5.xlarge
    node_labels:
    - infra
    - infra-efk
    zone_suffixes:
      - a
      - b
      - c
    name_identifier: infra-efk
  include_role:
    name: machineset
# https://access.redhat.com/solutions/4233311
- name: Set the default node selector to application - can be overridden with ns annotations
  k8s:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
    api_version: config.openshift.io/v1
    merge_type: merge
    kind: Scheduler
    name: cluster
    definition:
      spec:
        defaultNodeSelector: 'node-role.kubernetes.io/application='
