---

- name: '[OCP4-AUTO-INSTALL][PREREQS] Download the required tooling'
  get_url:
    url: "{{ aws_installer }}"
    dest: "{{ user_path }}/awscli-exe-linux-x86_64.zip"
  register: awsclifile

- name: '[OCP4-AUTO-INSTALL][PREREQS] Create a user-writable directory for tools'
  file:
    name: "{{ user_path }}/tools"
    state: directory

- name: '[OCP4-AUTO-INSTALL][PREREQS] Unarchive the aws tools'
  unarchive:
    src: "{{ user_path }}/awscli-exe-linux-x86_64.zip"
    dest: "{{ user_path }}/tools"
  when: awsclifile.changed
