---

- name: '[OCP4-AUTO-INSTALL][PREREQS] Create a user-writable directory for tools'
  file:
    name: "{{ item }}/.aws"
    state: directory
  loop:
    - "{{ user_path }}"

- name: '[OCP4-AUTO-INSTALL][PREREQS] Deploy default aws credentials for this bastion'
  template:
    src: templates/credentials.j2
    dest: "{{ item }}/.aws/credentials"
  loop:
    - "{{ user_path }}"
