














- name: '[OCP4-AUTO-INSTALL][PREREQS] Set in the environment where aws lives'
  lineinfile:
    path: ~/.bash_profile
    line: "{{ line }}"
  loop:
    - 'export PATH=$PATH:{{ container_dir }}/tools/aws/dist/'
    - 'export AWS_SECRET_ACCESS_KEY="{{ aws_secret_access_key }}"'
    - 'export AWS_ACCESS_KEY_ID="{{ aws_access_key_id }}"'
  loop_control:
    loop_var: line

# TODO: review if is needed
- name: '[OCP4-AUTO-INSTALL][PREREQS] Create a directory for the installation'
  file:
    name: "{{ user_path }}"
    state: directory

- name: '[OCP4-AUTO-INSTALL][PREREQS] Create a user-writable directory for tools'
  file:
    name: "{{ item }}/.aws"
    state: directory
  loop:
    - "{{ container_dir }}"
    - "{{ user_path }}"

# Deploy AWS Creds inside of the container and in the playbook dir
- name: '[OCP4-AUTO-INSTALL][PREREQS] Deploy default aws credentials for this bastion'
  template:
    src: templates/credentials.j2
    dest: "{{ item }}/.aws/credentials"
  loop:
    - "{{ container_dir }}"
    - "{{ user_path }}"
