---

- name: '[OCP4-AUTO-INSTALL][PREREQS] Create a user-writable directory for tools'
  file:
    name: "~/.aws"
    state: directory

- name: '[OCP4-AUTO-INSTALL][PREREQS] Define aws credentials for the installation'
  template:
    src: templates/credentials.j2
    dest: "~/.aws/credentials"
