---

- name: '{{ cmanager_label }} Install namespace'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/ns.yml.j2


- name: "{{ cmanager_label }} Add stable chart repo"
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
  environment:
    K8S_AUTH_CONTEXT: "{{ kubeconfig }}"


- name: "{{ cmanager_label }} Get certmanager CRDs"
  get_url:
    url:  "https://github.com/jetstack/cert-manager/releases/download/{{ cmanager_chart_version }}/cert-manager.crds.yaml"
    dest: "{{user_path}}/certMancrd.yaml"


- name: "{{ cmanager_label }} Add certmanager CRDs"
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', '{{user_path}}/certMancrd.yaml') }}"


- name: '{{ cmanager_label }} Deploy certmanager'
  community.kubernetes.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: cert-manager
    namespace:  "{{ cmanager_namespace }}"
    chart_ref: jetstack/cert-manager
    chart_version: '{{ cmanager_chart_version }}'
    release_state: '{{ cmanager_state }}'
    wait: yes
    values:
      replicas: 3
  register: operator

- name: '{{ cmanager_label }} Waiting running pods'
  pause:
    seconds: 30

- name: '{{ cmanager_label }} Reach Dns Challenge adding dns nameserver'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: "{{ cmanager_namespace }}"
    definition: "{{ lookup('file', item ) | from_yaml }}"
    merge_type: merge
  loop:
  - ./files/cert-manager-dns.yml
