---
# vars file for ocp4tools
var_installer_baseurl: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp4_version }}'
var_installer_program: 'openshift-install-linux-{{ ocp4_version }}.tar.gz'
var_installer_clienttools: 'openshift-client-linux-{{ ocp4_version }}.tar.gz'

 files_to_encrypt:
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install_state.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfvars.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.aws.auto.tfvars.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeconfig"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeadmin-password"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.key"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.crt"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/metadata.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfstate"
 files_to_archive:
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install_state.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install.log"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfvars.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.aws.auto.tfvars.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeconfig"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeadmin-password"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.key"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.crt"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/metadata.json"
     - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfstate"
