---

#https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-htpasswd-identity-provider.html

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Generate htpasswd hash for ocp4_idm_htpasswd_user_password'
  shell: >-
    htpasswd -nb "userN" "{{ ocp4_idm_htpasswd_user_password }}"|cut -d: -f2
  register: htpasswd_line
  when:
  - ocp4_idm_htpasswd_user_password is defined
  - ocp4_idm_htpasswd_user_password_hash is not defined

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Set fact ocp4_idm_htpasswd_user_password_hash'
  set_fact:
    ocp4_idm_htpasswd_user_password_hash: "{{ htpasswd_line.stdout }}"
  when:
  - ocp4_idm_htpasswd_user_password is defined
  - ocp4_idm_htpasswd_user_password_hash is not defined
  - htpasswd_line is succeeded

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Generate htpasswd hash for ocp4_idm_admin_user'
  shell: >-
    htpasswd -nb "admin" "{{ ocp4_idm_htpasswd_admin_password }}"|cut -d: -f2
  register: htpasswd_line
  when:
  - ocp4_idm_htpasswd_admin_password is defined
  - ocp4_idm_htpasswd_admin_password_hash is not defined

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Set fact ocp4_idm_htpasswd_admin_password_hash'
  set_fact:
    ocp4_idm_htpasswd_admin_password_hash: "{{ htpasswd_line.stdout }}"
  when:
  - ocp4_idm_htpasswd_admin_password is defined
  - ocp4_idm_htpasswd_admin_password_hash is not defined
  - htpasswd_line is succeeded

# TODO: '[OCP4-POST-OAUTH] locate better the htpasswd
- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Generate htpasswd file'
  template:
    src: "htpasswd.j2"
    dest: "{{ user_path }}/users.htpasswd"
    #owner: "{{ ansible_user }}"
    mode: 0664

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Ensure htpasswd Secret is absent'
  k8s:
    kubeconfig: "{{ user_path }}/auth/kubeconfig"
    state: absent
    api_version: v1
    kind: Secret
    name: htpasswd-secret
    namespace: openshift-config

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Create htpasswd secret from htpasswd file'
  shell: "{{ container_dir }}/tools/oc create secret generic htpasswd-secret -n openshift-config --from-file=htpasswd={{ user_path }}/users.htpasswd"
  environment:
    KUBECONFIG: "{{ user_path }}/auth/kubeconfig"

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Update OAuth Configuration'
  k8s:
    kubeconfig: "{{ user_path }}/auth/kubeconfig"
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/oauth-htpasswd.yaml

#- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Create htpasswd secret from htpasswd file'
#  shell: "{{ container_dir }}/tools/oc adm add-cluster-role-to-user cluster-admin {{ ocp4_idm_admin_user }}"
#  environment:
#    KUBECONFIG: "{{ user_path }}/auth/kubeconfig"

- name: '[OCP4-POST-OAUTH] Set up Cluster Admin User'
  when: ocp4_idm_admin_user is defined
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', './templates/cluster_role_binding.j2') | from_yaml }}"

- name: '[OCP4-POST-OAUTH][OCP4-HTPASSWD] Print User Information'
  debug:
    msg: "{{ item }}"
  loop:
  - "user.info: HTPasswd Authentication is enabled on this cluster."
  - "user.info: {{ ocp4_idm_htpasswd_user_base }}1 .. {{ ocp4_idm_htpasswd_user_base }}{{ ocp4_idm_htpasswd_user_count }} are created."
  - "user.info: User `{{ ocp4_idm_admin_user }}` is a cluster-admin"

# More Info: https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-basic-authentication-identity-provider.html
