---

- name: '[OCP4_AUTO_INSTALL][OCP4-POSTINSTALL][INFRA-NODES] Interrogate cluster'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: infradata

- name: '[OCP4_AUTO_INSTALL][OCP4-POSTINSTALL][INFRA-NODES] Capture nodes'
  k8s_facts:
    kubeconfig: "{{ kubeconfig }}"
    kind: Node
  register: nodedata

- name: '[OCP4_AUTO_INSTALL][OCP4-POSTINSTALL][INFRA-NODES] Apply the application label to the worker nodes'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Node
    name: "{{ node.metadata.name }}"
    definition:
      metadata:
        labels:
          '{{ worker_label }}': ""
          #node-role.kubernetes.io/infra: ""
  loop: "{{ nodedata.resources }}"
  loop_control:
    loop_var: node
  when:
    - node.metadata.labels['node-role.kubernetes.io/worker'] is defined
    - node.metadata.labels['node-role.kubernetes.io/infra'] is not defined

# Grab the machinesets
- name: '[OCP4_AUTO_INSTALL][OCP4-POSTINSTALL][INFRA-NODES] Grab the machinesets'
  k8s_facts:
    kubeconfig: "{{ kubeconfig }}"
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets

- name: '[OCP4_AUTO_INSTALL][OCP4-POSTINSTALL][INFRA-NODES] Apply the same label to the default worker machineset stanza'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "{{ machineset.metadata.name }}"
    namespace: openshift-machine-api
    definition:
      spec:
        template:
          spec:
            metadata:
              labels:
                '{{ worker_label }}': ""
  loop: "{{ machinesets.resources }}"
  loop_control:
    loop_var: machineset
  when: machineset.metadata.name is search ("worker")
