---
- name: '[OCP4-AUTO-INSTALL][PREREQS-OCPTOOLS]  Download the required ocp4 tooling'
  get_url:
    url: "{{ var_installer_baseurl }}{{ pkg }}"
    dest: "{{ container_dir }}/{{ pkg }}"
  loop:
    - "{{ var_installer_program }}"
    - "{{ var_installer_clienttools }}"
  loop_control:
    loop_var: pkg

- name: '[OCP4-AUTO-INSTALL][PREREQS-OCPTOOLS] Create a user-writable directory for tools'
  file:
    name: "{{ container_dir }}/tools"
    state: directory

 - name: '[OCP4-AUTO-INSTALL][PREREQS-OCPTOOLS]  Ensure downloaded installers are unarchived'
  unarchive:
    src: "{{ container_dir }}/{{ pkg }}"
    dest: "{{ container_dir }}/tools/"
  loop:
    - "{{ var_installer_program }}"
    - "{{ var_installer_clienttools }}"
  loop_control:
    loop_var: pkg

- name: '[OCP4-AUTO-INSTALL][PREREQS-OCPTOOLS]  Set in the environment where cluster installer tools live'
  lineinfile:
    path: "{{ container_dir }}/.bash_profile"
    line: "{{ linetoadd }}"
  loop:
    - "export KUBECONFIG={{ container_dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeconfig"
    - export PATH=$PATH:{{ container_dir }}/tools/
  loop_control:
    loop_var: linetoadd
