---

- import_tasks: download.yml

- import_tasks: create_config.yaml

- import_tasks: install.yml

- import_tasks: uninstall.yaml
  tags: uninstall
  when: uninstall_ocp is defined and uninstall_ocp== "true"
