- name: Add helm repo
  kubernetes.core.helm_repository:
    name: rhacs
    url: "https://mirror.openshift.com/pub/rhacs/charts/"

- name: Deploy Central
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: stackrox-central-services
    chart_ref: rhacs/central-services
    release_namespace: stackrox
    values: "{{ lookup('template', 'templates/central.yml.j2') | from_yaml }}"
    create_namespace: true

- name: Get central route
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Route
    api_version: route.openshift.io/v1
    namespace: stackrox
    name: central
  register: r_stackrox_central_route
  retries: 10
  delay: 20

- name: Store central route as a fact
  set_fact:
    f_stackrox_central_addr: "{{ r_stackrox_central_route.resources[0].spec.host }}"

- name: Wait for Central availability
  uri:
    url: "https://{{ f_stackrox_central_addr }}/v1/ping"
    method: GET
    user: admin
    password: "{{ stackrox_central_admin_password }}"
    force_basic_auth: true
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 15
  delay: 20
