---

- name: '[POSTINSTALL][MONITORING] Apply cluster-monitoring-config config map'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', 'cluster-monitoring-config.yml') }}"

